sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
script:
- apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442
- sudo apt-get install -y libsnappy-dev libncurses5-dev libgmp-dev libcurl3-dev zlib1g-dev curl unzip netbase  
- sudo curl -O -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64.tar.gz 
- sudo tar zxf stack-2.1.3-linux-x86_64.tar.gz -C /usr/local/bin stack-2.1.3-linux-x86_64/stack --strip 1 
- sudo curl -O -L https://github.com/google/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip  
- sudo unzip -d /usr/local protoc-3.9.1-linux-x86_64.zip bin/protoc 
- sudo chmod 755 /usr/local/bin/protoc 
- sudo curl -O https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz 
- sudo tar zxf libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz -C /usr/local 
- ldconfig 
- stack setup
- stack test
cache:
  directories:
  - $HOME/.stack